// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProductData is an autogenerated mock type for the ProductData type
type ProductData struct {
	mock.Mock
}

// DeleteItemData provides a mock function with given fields:
func (_m *ProductData) DeleteItemData() {
	_m.Called()
}

// GetAllItemData provides a mock function with given fields:
func (_m *ProductData) GetAllItemData() {
	_m.Called()
}

// GetItemData provides a mock function with given fields:
func (_m *ProductData) GetItemData() {
	_m.Called()
}

// PostCartData provides a mock function with given fields:
func (_m *ProductData) PostCartData() {
	_m.Called()
}

// PostItemData provides a mock function with given fields:
func (_m *ProductData) PostItemData() {
	_m.Called()
}

// UpdateItemData provides a mock function with given fields:
func (_m *ProductData) UpdateItemData() {
	_m.Called()
}

type mockConstructorTestingTNewProductData interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductData creates a new instance of ProductData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductData(t mockConstructorTestingTNewProductData) *ProductData {
	mock := &ProductData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
